# Generated by Django 4.0.3 on 2022-09-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_sizevariant_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='price',
            field=models.IntegerField(),
        ),
    ]
